[mysqld]
# The TCP/IP Port the MySQL Server will listen on
port=3306

#Path to installation directory. All paths are usually resolved relative to this.
basedir="D:/xampp1/mysql"

#Path to the database root
datadir="D:/xampp1/mysql/data"

# The default character set that will be used when a new schema or table is
# created and no character set is defined
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci

# The default storage engine that will be used when create new tables
default-storage-engine=INNODB

# The maximum amount of concurrent sessions the MySQL server will
# allow. One of these connections will be reserved for a user with
# SUPER privileges to allow the administrator to login even if the
# connection limit has been reached.
max_connections=151

# Query cache is used to cache SELECT results and later return them
# without actual executing the same query once again. Having the query
# cache enabled may result in significant speed improvements, if your
# have a lot of identical queries and rarely changing tables. See the
# "Qcache_lowmem_prunes" status variable to check if the current value
# is high enough for your load.
query_cache_size=16M

# Force IPv4 only and skip DNS reverse lookup
bind-address = 127.0.0.1
skip-name-resolve

# Try number of CPU's*2 for thread_concurrency
thread_concurrency=4

# Disable SSL
skip-ssl

# Skip networking if only used locally
# skip-networking

# Reduce memory usage
key_buffer_size=16M
max_allowed_packet=4M
table_open_cache=64
sort_buffer_size=512K
net_buffer_length=8K
read_buffer_size=256K
read_rnd_buffer_size=512K
myisam_sort_buffer_size=8M 